interfaces:
  - name: wg0
    description: ''
    addresses: ['192.168.255.1/24']
    networks: ['192.168.255.0/24']
    private_key: ''
    listen_port: 54321
    peers: 
      - public_key: ''
        private_key: ''
        peer_addresses: ['192.168.255.2/24']
        peer_networks: ['192.168.255.0/24']
        server_keepalive: 15
        peer_keepalive: 15
        server_allowed_ips: ['192.168.255.0/24']
        peer_allowed_ips: ['192.168.255.0/24']
        peer_description: peer A
        peer_endpoint: ''
        server_endpoint: ''
        peer_listen_port: 54321